### ISSUE TITLE
Build issues in pip 10.0

### ISSUE THREAD

**Issue by vdboor** [Nekmo/python-akismet#7]
The import `from pip.req import parse_requirements` is no longer available. This causes the `setup.py` call to fail on pip 10.0

Since the only requirement is the `requests` library, it's probably a better idea to include that directly in setup.py: `install_requires=['requests']`

**Comment by Nekmo** [comment]
Thanks for the issue, today it will be solved.

**Comment by Nekmo** [comment]
Fixed. Thank you for your issue. :)

**Comment by vdboor** [comment]
Thanks for the quick response!
